---
name: reusable
on:
  workflow_dispatch:
jobs:
  reusable-workflow:
    uses: Luck858/remoterepo/.github/workflows/reusable.yaml@main
    with:
      java-version: "21"
      mvn-command: mvn clean package
